# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCarListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_charge', models.FloatField(default=0.0, verbose_name='Minum Fare for Trip')),
                ('maximum_hours', models.IntegerField(default=12, verbose_name='Maxmum  hours for Trip')),
                ('maximum_km', models.IntegerField(default=250, verbose_name='Maximum KM for Trip')),
                ('charge_per_extra_hours', models.FloatField(default=120, verbose_name='Extra per hours charge')),
                ('night_drive_charge', models.IntegerField(default=0, verbose_name='For Night time driving from 11PM to 5 AM')),
                ('per_km_charge', models.FloatField(default=9, verbose_name='Minum Fare for Trip')),
                ('ac_charges', models.FloatField(default=1, verbose_name='Minum Fare for Trip')),
                ('details', models.TextField(verbose_name='Extra details')),
                ('tac', models.TextField(verbose_name='Term and condition ')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Brand')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_listings', to='cities.City')),
            ],
            options={
                'verbose_name': 'Car Listing',
                'verbose_name_plural': 'Cars Listing',
            },
        ),
    ]
