# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_rentalcarlisting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cateogory',
            options={'verbose_name': 'Car Type', 'verbose_name_plural': 'Car Types'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
        migrations.AddField(
            model_name='brand',
            name='car_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='car.Car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='car.Cateogory'),
            preserve_default=False,
        ),
    ]
