# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20160811_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcarlisting',
            name='ac_charges',
            field=models.FloatField(default=1, verbose_name='AC Charge per KM'),
        ),
        migrations.AlterField(
            model_name='rentalcarlisting',
            name='per_km_charge',
            field=models.FloatField(default=9, verbose_name='Per KM Charge'),
        ),
    ]
